### ISSUE TITLE
does not accept keystrokes and mouse coordinates

### ISSUE THREAD

**Issue by Ondrik8** [ichisadashioko/mirror-input#1]
Hello, I launched the Server code on the VPS Windows 2012, then the client code on the VPS Windows Server 2012 on both is Python 3.10, the connection was successful, it can be seen that the server code sends actions to the client server, but it does not respond to keystrokes and mouse actions in the server VPS
![Screenshot_2](https://user-images.githubusercontent.com/59111771/169495821-0d643a32-e86c-42e7-a51f-6667cec872db.png)
![Screenshot_3](https://user-images.githubusercontent.com/59111771/169495963-33d7ecd3-5787-4499-a76f-07cd0cda6e04.png)

**Comment by ichisadashioko** [comment]
When we start the server, it will be paused. Press `F3` to toggle the pause state. In the server code, it prints `True` to indicate the `PAUSE_FLAG` current value.

**Comment by Ondrik8** [comment]
> Когда мы запустим сервер, он будет приостановлен. Нажмите `F3`, чтобы переключить состояние паузы. В коде сервера он печатает, `True`чтобы указать `PAUSE_FLAG`текущее значение.

oh Thanks its works))
